/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shaswat_mobilevo_LibVisodo */

#ifndef _Included_com_example_shaswat_mobilevo_LibVisodo
#define _Included_com_example_shaswat_mobilevo_LibVisodo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shaswat_mobilevo_LibVisodo
 * Method:    start
 * Signature: (JJI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_shaswat_mobilevo_LibVisodo_start(JNIEnv *, jobject, jlong addrRgba, jlong afterPic, jint i);

/*
 * Class:     com_example_shaswat_mobilevo_LibVisodo
 * Method:    init
 * Signature: (JJ)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_shaswat_mobilevo_LibVisodo_init(JNIEnv *, jobject, jlong firstPic, jlong secondPic);

#ifdef __cplusplus
}
#endif
#endif
